openapi: 3.0.2
info:
  title: Unical - Ricerca
  version: 0.1.2
  servers:
  - description: description
    url: storage.portale.unical.it
  - description: description
    url: ricerca.unical.it
  tags:
  - description: description
    name: public
  contact:
  - email: giuseppe.demarco@unical.it
    name: Giuseppe De Marco
    url: https://github.com/UniversitaDellaCalabria
  description: OpenData per la Ricerca in Unical
paths:
  /api/ricerca/docenti:
    get:
      operationId: listDocentes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Docente'
          description: ''
      tags:
      - api
  /api/ricerca/docente/{id}:
    get:
      operationId: retrieveDocente
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this docente.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Docente'
          description: ''
      tags:
      - api
  /api/ricerca/aster/1:
    get:
      operationId: listRicercaAster1s
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaAster1'
          description: ''
      tags:
      - api
  /api/ricerca/aster/1/{id}:
    get:
      operationId: retrieveRicercaAster1
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca aster1.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaAster1'
          description: ''
      tags:
      - api
  /api/ricerca/aster/2:
    get:
      operationId: listRicercaAster2s
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaAster2'
          description: ''
      tags:
      - api
  /api/ricerca/aster/2/{id}:
    get:
      operationId: retrieveRicercaAster2
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca aster2.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaAster2'
          description: ''
      tags:
      - api
  /api/ricerca/erc/1:
    get:
      operationId: listRicercaErc1s
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaErc1'
          description: ''
      tags:
      - api
  /api/ricerca/erc/1/{id}:
    get:
      operationId: retrieveRicercaErc1
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca erc1.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaErc1'
          description: ''
      tags:
      - api
  /api/ricerca/erc/2:
    get:
      operationId: listRicercaErc2s
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaErc2'
          description: ''
      tags:
      - api
  /api/ricerca/erc/2/{id}:
    get:
      operationId: retrieveRicercaErc2
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca erc2.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaErc2'
          description: ''
      tags:
      - api
  /api/ricerca/docente/gruppo:
    get:
      operationId: listRicercaDocenteGruppos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaDocenteGruppo'
          description: ''
      tags:
      - api
  /api/ricerca/docente/gruppo/{id}:
    get:
      operationId: retrieveRicercaDocenteGruppo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca docente gruppo.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaDocenteGruppo'
          description: ''
      tags:
      - api
  /api/ricerca/docente/linea_applicata:
    get:
      operationId: listRicercaDocenteLineaApplicatas
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaDocenteLineaApplicata'
          description: ''
      tags:
      - api
  /api/ricerca/docente/linea_applicata/{id}:
    get:
      operationId: retrieveRicercaDocenteLineaApplicata
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca docente linea
          applicata.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaDocenteLineaApplicata'
          description: ''
      tags:
      - api
  /api/ricerca/docente/linea_base:
    get:
      operationId: listRicercaDocenteLineaBases
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaDocenteLineaBase'
          description: ''
      tags:
      - api
  /api/ricerca/docente/linea_base/{id}:
    get:
      operationId: retrieveRicercaDocenteLineaBase
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca docente linea
          base.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaDocenteLineaBase'
          description: ''
      tags:
      - api
  /api/ricerca/gruppo:
    get:
      operationId: listRicercaGruppos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaGruppo'
          description: ''
      tags:
      - api
  /api/ricerca/gruppo/{id}:
    get:
      operationId: retrieveRicercaGruppo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca gruppo.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaGruppo'
          description: ''
      tags:
      - api
  /api/ricerca/linea_applicata:
    get:
      operationId: listRicercaLineaApplicatas
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaLineaApplicata'
          description: ''
      tags:
      - api
  /api/ricerca/linea_applicata/{id}:
    get:
      operationId: retrieveRicercaLineaApplicata
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca linea applicata.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaLineaApplicata'
          description: ''
      tags:
      - api
  /api/ricerca/linea_base:
    get:
      operationId: listRicercaLineaBases
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RicercaLineaBase'
          description: ''
      tags:
      - api
  /api/ricerca/linea_base/{id}:
    get:
      operationId: retrieveRicercaLineaBase
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this ricerca linea base.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RicercaLineaBase'
          description: ''
      tags:
      - api
components:
  schemas:
    Docente:
      type: object
      properties:
        nome:
          type: string
          maxLength: 200
        cognome:
          type: string
          maxLength: 200
      required:
      - nome
      - cognome
    RicercaAster1:
      type: object
      properties:
        descrizione:
          type: string
          maxLength: 200
      required:
      - descrizione
    RicercaAster2:
      type: object
      properties:
        descrizione:
          type: string
          maxLength: 200
      required:
      - descrizione
    RicercaErc1:
      type: object
      properties:
        cod_erc1:
          type: string
          maxLength: 40
        descrizione:
          type: string
          maxLength: 200
      required:
      - cod_erc1
      - descrizione
    RicercaErc2:
      type: object
      properties:
        cod_erc2:
          type: string
          maxLength: 60
        descrizione:
          type: string
          maxLength: 200
        ricerca_erc1:
          type: string
          nullable: true
      required:
      - cod_erc2
      - descrizione
    RicercaDocenteGruppo:
      type: object
      properties:
        docente:
          type: string
          nullable: true
        ricerca_gruppo:
          type: string
        dt_inizio:
          type: string
          format: date-time
          nullable: true
        dt_fine:
          type: string
          format: date-time
          nullable: true
      required:
      - ricerca_gruppo
    RicercaDocenteLineaApplicata:
      type: object
      properties:
        docente:
          type: string
          nullable: true
        ricerca_linea_applicata:
          type: string
          nullable: true
        dt_inizio:
          type: string
          format: date-time
          nullable: true
        dt_fine:
          type: string
          format: date-time
          nullable: true
    RicercaDocenteLineaBase:
      type: object
      properties:
        docente:
          type: string
          nullable: true
        ricerca_linea_base:
          type: string
          nullable: true
        dt_inizio:
          type: string
          format: date-time
          nullable: true
        dt_fine:
          type: string
          format: date-time
          nullable: true
    RicercaGruppo:
      type: object
      properties:
        nome:
          type: string
          maxLength: 200
        descrizione:
          type: string
          maxLength: 2000
      required:
      - nome
      - descrizione
    RicercaLineaApplicata:
      type: object
      properties:
        descrizione:
          type: string
          maxLength: 400
        ricerca_aster2:
          type: string
        descr_pubblicaz_prog_brevetto:
          type: string
          nullable: true
          maxLength: 1000
        anno:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
      required:
      - descrizione
      - ricerca_aster2
    RicercaLineaBase:
      type: object
      properties:
        descrizione:
          type: string
          maxLength: 400
        ricerca_erc2:
          type: string
        descr_pubblicaz_prog_brevetto:
          type: string
          nullable: true
          maxLength: 1000
        anno:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
      required:
      - descrizione
      - ricerca_erc2
